version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    image: "${IMG_NAME}:${TAG}"
    container_name: "${APP_NAME}-${TAG}"
    environment:
      - TZ=${TZ}
    ports:
      - "${EXP_PORT}:${APP_PORT}"
    networks:
      - app_network
    env_file:
      - docker.env
    restart: unless-stopped
    # volumes:
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    #     reservations:
    #       memory: 256M

networks:
  app_network:
    name: "${APP_NETWORK}-${TAG}"
    driver: bridge
